FirstFileName: "pp_files/init.pp"
SecondFileName: "pp_files/init_upstream.pp"
ThirdFileName: "pp_files/heat.pp"
FirstClassName: "heat"
SecondClassName: "heat"
ThirdClassName: "openstack::heat"

# Replace item in second class if it's in
# the first class
ReplaceOnMerge: True
# Get difference between first class
# and second with items which only names of
# parameters are different
DiffOnlyParamNames: True
# Get same class2 to class1 fileds
# only when names of parameters
# are equal
SameOnlyParamNames: True

# If "True" then syncing of classes
# will be made
SyncClasses: True
# Allowed: "merge", "diff", "same", "sync"
ActionsToDo: ["diff"]